### ISSUE TITLE
TMVCJsonDataObjectsSerializer : should calls "ADataSet.first"  ?

### ISSUE THREAD

**Issue by drcrck** [danieleteti/delphimvcframework#729]
Hi Daniele, 
This bug report stars from far far away :) :) 

I have a mustache view, and in prevoius dvmc framework this code works well:

```
   ViewData ['dati'] := myQuery;
   LoadView(['header','body','footer']);
```

"dati" is managed only in body part of my views. 

With last update it results in a empty html body , so I have done some debug. 
The problem is that "header" view eats my ViewData! when  dmvc engine starts to render the second view (body),  my data is empty. 

This workaround works well: 
```
   LoadView(['header']);
   ViewData ['dati'] := myQuery;
   LoadView(['body']);
   LoadView(['footer']);

```

it just look into code and find the problem, that's reported on my title :) 
DataSetToJsonArray  ( but not only this method) never call "first" to dataSet , so in my case it's already to EOF after the first view render , and when i really need my data, seialization returns an empty array []  ;

**Comment by danieleteti** [comment]
Hi, which version are you using? Can you reproduce the problem with the latest dmvc version?

**Comment by drcrck** [comment]
Hi Daniele, 
issue is still present, with last version.

```
   qTmp.SQL.LoadFromFile( filename );
   qTmp.Open ;
   ViewData ['dati'] := qtmp ;
//-> same if    ViewDataset ['dati'] := qtmp ;
   LoadView(['header','body','footer']);
   RenderResponseStream;

```
It draws header and footer ( simple html tags ) and body without mustache part expanded. 
in body , all "{#dati}}" section is empty. 

this simple workaround works  :

```
   ViewData ['dati'] := qTmp;
   LoadView(['header']);
   qTmp.First ;    // <--  reset to first;
   LoadView([nome]);
   LoadView(['footer']);

```

in , MVCFramework.View.Renderers.Mustache, method PrepareModels ,  LoadView move the actual record to Eof , so the nexr "loadview" is empty.

**Comment by danieleteti** [comment]
This issue has been fixed, howeer I strongly suggest to switch to functional actions. Check the updated `serversideviewmustache` sample.

**Comment by drcrck** [comment]
Hi Daniele! 
i update dmvc just now, but issue is still present. 

i change my code in this way , and now it works:

```
   ViewData ['dati'] := qTmp;
   SetPagesCommonHeaders(['header']) ;
   SetPagesCommonFooters(['footer']);
   Render(Page(['body'] ));
```

but method "DataSetToJsonArray" maybe have still the "first" problem...
